### ISSUE TITLE
Publish docs at readthedocs

### ISSUE THREAD

**Issue by blankdots** [CSCfi/beacon-python#11]
#### Description

github.io docs are ok, but are not automatically built every time. We can use readthedocs for that.
Might need custom `readthedocs.yml`
```yml
formats:
    - none
build:
    image: latest
python:
   version: 3.6
   setup_py_install: True
   extra_requirements:
        - docs
```

#### DoD (Definiton of Done)

Documentation automatically built at readthedocs.org

#### Testing

Peer review, able to view docs at custom readthedocs.org address
